---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Dylan Malandain.
--- DateTime: 29/10/2019 02:40
---

---@class RageUI
RageUI = {}

---@class UIMenu
UIMenu = {}

---@class Item
RageUI.Item = {}

---@class Panel
RageUI.Panel = {}

---@class Window
RageUI.Window = {}

---@class Panels
Panels = {}

setmetatable({}, {__index = Panels})

---@class Items
Items = {}

setmetatable({}, {__index = Items})

local random = math.random

---Shared function
---@param template string ex: '4xxx-yxxx'
function RageUI.uuid(template)
    local template = template or 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'
    return string.gsub(template, '[xy]', function (c)
        local v = (c == 'x') and random(0, 0xf) or random(8, 0xb)
        return string.format('%x', v)
    end)
end

